export const EXTENSION_MESSAGES = Object.freeze({
  DOWNLOAD_WEBINAR: "DOWNLOAD_WEBINAR",
  OPEN_HOMEWORK_FOLDER: "OPEN_HOMEWORK_FOLDER",
  DOWNLOAD_HOMEWORK_MATERIALS: "DOWNLOAD_HOMEWORK_MATERIALS",
  READ_HOMEWORK_RESULTS: "READ_HOMEWORK_RESULTS",
  OPEN_HOMEWORK_WARP: "OPEN_HOMEWORK_WARP",
  OPEN_GOOGLE_SHEET: "OPEN_GOOGLE_SHEET",
  GOOGLE_SHEET_READY: "GOOGLE_SHEET_READY",
});

export const LOCAL_COMMANDS = Object.freeze({
  OPEN_FOLDER: "open_folder",
  OPEN_WARP: "open_warp",
  READ_LATEST_ANALYSIS: "read_latest_analysis",
  CLONE_STUDENT_MATERIALS: "clone_student_materials",
});

const LOCAL_SERVER_HOST = "127.0.0.1";
const LOCAL_SERVER_PORT = 8765;
const LOCAL_COMMANDS_PATH = "/commands";
const LOCAL_ZIP_EXTRACTION_PATH = "/zip-extraction";
const LOCAL_STATIC_FILE_UPLOAD_PATH = "/static-file";

export const LOCAL_SERVER = Object.freeze({
  HOST: LOCAL_SERVER_HOST,
  PORT: LOCAL_SERVER_PORT,
  COMMANDS_PATH: LOCAL_COMMANDS_PATH,
  ZIP_EXTRACTION_PATH: LOCAL_ZIP_EXTRACTION_PATH,
  STATIC_FILE_UPLOAD_PATH: LOCAL_STATIC_FILE_UPLOAD_PATH,
  HEALTH_PATH: "/health",
  COMMANDS_URL: `http://${LOCAL_SERVER_HOST}:${LOCAL_SERVER_PORT}${LOCAL_COMMANDS_PATH}`,
  ZIP_EXTRACTION_URL: `http://${LOCAL_SERVER_HOST}:${LOCAL_SERVER_PORT}${LOCAL_ZIP_EXTRACTION_PATH}`,
  STATIC_FILE_UPLOAD_URL: `http://${LOCAL_SERVER_HOST}:${LOCAL_SERVER_PORT}${LOCAL_STATIC_FILE_UPLOAD_PATH}`,
});

export const SESSION_STORAGE_KEYS = Object.freeze({
  PENDING_GOOGLE_SHEET_TAB_ID: "pendingGoogleSheetTabId",
});

export const GOOGLE_SHEET_URL = "https://sheets.new";
